### ISSUE TITLE
undefined symbol: ASIInitCamera

### ISSUE THREAD

**Issue by robspearman** [python-zwoasi/python-zwoasi#2]
I am on Linux.  I downloaded the latest SDK from ZWO (V0.3.0727) but there is no function "ASIInitCamera" in any of their libraries.  Is there a different API for Linux?

```
python zwoasi_demo.py
Traceback (most recent call last):
  File "./zwoasi_demo.py", line 5, in <module>
    import zwoasi as asi
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/zwoasi/__init__.py", line 690, in <module>
    zwolib.ASIInitCamera.argtypes = [c.c_int]
  File "/opt/rh/python27/root/usr/lib64/python2.7/ctypes/__init__.py", line 373, in __getattr__
    func = self.__getitem__(name)
  File "/opt/rh/python27/root/usr/lib64/python2.7/ctypes/__init__.py", line 378, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib64/asi/libASICamera2.so: undefined symbol: ASIInitCamera
```

**Comment by stevemarple** [comment]
I'm using version 0.4.0929 on Linux, downloaded from https://astronomy-imaging-camera.com/software/ on 17th November 2016. I see they have a newer version now for Linux and Mac (0.6.0110), I'll test in the next few days.

**Comment by stevemarple** [comment]
@robspearman Is this issue fixed for you with a later version?

**Comment by iromero91** [comment]
Closing this for inactivity.
